import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Disclosure, Transition } from "@headlessui/react";
import { Hero } from '@/components/hero';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const data = [
    {
      id: 1,
      question: "Is this component completely free to use?",
      answer: "No, it should be purchased first.",
    },
    {
      id: 2,
      question: "Can I use it in a commercial project?",
      answer: "Yes, once purchased, you can use it in any projects.",
    },
    {
      id: 3,
      question: "What is your refund policy?",
      answer:
        "If you are unhappy with your purchase for any reason, email us within 90 days and we wll refund you in full, no questions asked.",
    },
    {
      id: 4,
      question: "Do you offer technical support?",
      answer:
        "No, we don't offer technical support for components. Please purchase a support plan to get 6 months of support.",
    },
  ];


  return (
    <>
      <Head>
        <title>Viewer Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-screen-xl m-auto'>
        <Hero />
        <section className="pt-24 pb-28 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <h2 className="mb-7 text-6xl md:text-8xl xl:text-10xl font-bold font-heading text-center tracking-px-n leading-none">
              Inference analysis made easy
            </h2>
            <p className="mb-14 text-lg text-gray-600 font-medium text-center mx-auto md:max-w-2xl">
              Looking to better analyze medical volumes or understand your AI model's inference? Our private,
              zero-footprint, web based renderer can help.
            </p>
            <div className="flex justify-center">
              <div className="inline-block">
                <img className="mb-11 mx-auto transform hover:translate-y-3 transition ease-in-out duration-1000" src="viewer_example.png" alt="" />
                <ul className="flex flex-wrap justify-center -m-8">
                  <li className="w-auto p-8">
                    <a className="text-sm text-indigo-600 hover:text-indigo-700 font-semibold uppercase tracking-px" href="#">Real-time Analytics</a>
                  </li>
                  <li className="w-auto p-8">
                    <a className="text-sm text-gray-400 hover:text-gray-500 font-semibold uppercase tracking-px" href="#">Easy Projects</a>
                  </li>
                  <li className="w-auto p-8">
                    <a className="text-sm text-gray-400 hover:text-gray-500 font-semibold uppercase tracking-px" href="#">Email Notification</a>
                  </li>
                  <li className="w-auto p-8">
                    <a className="text-sm text-gray-400 hover:text-gray-500 font-semibold uppercase tracking-px" href="#">Cloud Servers</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="relative pt-28 pb-36 bg-blueGray-100 overflow-hidden">
          <img className="absolute top-0 left-0" src="flaro-assets/images/logos/gradient3.svg" alt="" />
          <div className="relative z-10 container px-4 mx-auto">
            <p className="mb-14 text-sm text-gray-600 text-center font-semibold uppercase tracking-px">
              Powering next-gen companies
            </p>
            <div className="flex flex-wrap max-w-5xl mx-auto -m-3">
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl2.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl3.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl4.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl5.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl6.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl7.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl8.png" alt="" />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-36 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap xl:items-center -m-8">
              <div className="w-full md:w-1/2 p-8">
                <img className="mx-auto transform hover:translate-y-3 transition ease-in-out duration-1000" src="flaro-assets/images/features/upgrade.png" alt="" />
              </div>
              <div className="w-full md:w-1/2 p-8">
                <div className="md:max-w-xl">
                  <p className="mb-7 text-sm text-gray-600 font-semibold uppercase tracking-px">
                    👋 Meet new Flaro
                  </p>
                  <h2 className="mb-32 text-6xl md:text-7xl font-bold font-heading tracking-px-n leading-tight">
                    Upgrade to pro to unlock all features.
                  </h2>
                  <div className="flex flex-wrap mb-5 -m-8">
                    <div className="w-full md:w-1/2 p-8">
                      <div className="md:max-w-xs">
                        <div className="flex flex-wrap -m-2">
                          <div className="w-auto p-2">
                            <svg className="mt-1" width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M9 3V5M15 3V5M9 19V21M15 19V21M5 9H3M5 15H3M21 9H19M21 15H19M7 19H17C18.1046 19 19 18.1046 19 17V7C19 5.89543 18.1046 5 17 5H7C5.89543 5 5 5.89543 5 7V17C5 18.1046 5.89543 19 7 19ZM9 9H15V15H9V9Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          </div>
                          <div className="flex-1 p-2">
                            <h3 className="mb-2 text-xl font-semibold leading-normal">
                              Analytical
                            </h3>
                            <p className="text-gray-600 font-medium leading-relaxed">
                              Lorem ipsum dolor sit amet, to the consectr adipis.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="w-full md:w-1/2 p-8">
                      <div className="md:max-w-xs">
                        <div className="flex flex-wrap -m-2">
                          <div className="w-auto p-2">
                            <svg className="mt-1" width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M16 8V16M12 11V16M8 14V16M6 20H18C19.1046 20 20 19.1046 20 18V6C20 4.89543 19.1046 4 18 4H6C4.89543 4 4 4.89543 4 6V18C4 19.1046 4.89543 20 6 20Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          </div>
                          <div className="flex-1 p-2">
                            <h3 className="mb-2 text-xl font-semibold leading-normal">
                              Dashboards
                            </h3>
                            <p className="text-gray-600 font-medium leading-relaxed">
                              Lorem ipsum dolor sit amet, to the consectr adipis.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="md:inline-block">
                    <button className="py-4 px-6 w-full text-white font-semibold border border-indigo-700 rounded-xl shadow-4xl focus:ring focus:ring-indigo-300 bg-indigo-600 hover:bg-indigo-700 transition ease-in-out duration-200" type="button">
                      Get Started Now
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-32 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap items-center -m-8">
              <div className="w-full md:w-1/2 p-8">
                <h2 className="mb-9 text-6xl md:text-8xl xl:text-10xl font-bold font-heading tracking-px-n leading-none">
                  Get down to your business
                </h2>
                <p className="mb-10 text-lg text-gray-900 font-medium leading-relaxed md:max-w-md">
                  Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet
                  sint. Velit officia consequat duis enim velit mollit. Exercitation
                  veniam consequat.
                </p>
                <div className="mb-11 md:inline-block rounded-xl shadow-4xl">
                  <button className="py-4 px-6 w-full text-white font-semibold border border-indigo-700 rounded-xl focus:ring focus:ring-indigo-300 bg-indigo-600 hover:bg-indigo-700 transition ease-in-out duration-200" type="button">
                    Learn How to Save More
                  </button>
                </div>
                <div className="flex flex-wrap -m-2">
                  <div className="w-auto p-2">
                    <img src="flaro-assets/images/features/money-coins.png" alt="" />
                  </div>
                  <div className="flex-1 p-2">
                    <p className="text-gray-600 font-medium md:max-w-sm">
                      Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                      amet sint. Velit officia consequat duis enim velit mollit.
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 p-8">
                <img className="transform hover:-translate-x-16 transition ease-in-out duration-1000" src="flaro-assets/images/features/feature2.png" alt="" />
              </div>
            </div>
          </div>
        </section>
        <section className="relative pt-28 pb-24 bg-white overflow-hidden">
          <img className="absolute left-1/2 top-0 transform -translate-x-1/2" src="flaro-assets/images/how-it-works/gradient2.svg" alt="" />
          <div className="relative z-10 container px-4 mx-auto">
            <p className="mb-6 text-sm text-indigo-600 text-center font-semibold uppercase tracking-px">How this works</p>
            <h2 className="mb-20 text-3xl md:text-5xl text-center font-bold font-heading tracking-px-n leading-tight">We make things easy for you</h2>
            <div className="flex flex-wrap -m-8">
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-white w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={22} height={22} viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M2.75 9.16658H19.25M6.41667 13.7499H7.33333M11 13.7499H11.9167M5.5 17.4166H16.5C18.0188 17.4166 19.25 16.1854 19.25 14.6666V7.33325C19.25 5.81447 18.0188 4.58325 16.5 4.58325H5.5C3.98122 4.58325 2.75 5.81447 2.75 7.33325V14.6666C2.75 16.1854 3.98122 17.4166 5.5 17.4166Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                    <div className="hidden lg:block absolute left-12 top-1/2 transform -translate-y-1/2 w-96 h-px bg-gray-200" />
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">Import vti files</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat tempor con.</p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-white w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M16 8V16M12 11V16M8 14V16M6 20H18C19.1046 20 20 19.1046 20 18V6C20 4.89543 19.1046 4 18 4H6C4.89543 4 4 4.89543 4 6V18C4 19.1046 4.89543 20 6 20Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                    <div className="hidden lg:block absolute left-12 top-1/2 transform -translate-y-1/2 w-96 h-px bg-gray-200" />
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">Upload to viewer</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat tempor con.</p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-white w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={19} height={16} viewBox="0 0 19 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8.66717 2.54545V10.0455C8.66717 10.7841 8.52335 11.489 8.23571 12.1602C7.94807 12.8313 7.55922 13.4119 7.06916 13.902C6.5791 14.392 5.99849 14.7809 5.32733 15.0685C4.65616 15.3562 3.95126 15.5 3.21262 15.5H2.53081C2.34615 15.5 2.18635 15.4325 2.0514 15.2976C1.91646 15.1626 1.84899 15.0028 1.84899 14.8182V13.4545C1.84899 13.2699 1.91646 13.1101 2.0514 12.9751C2.18635 12.8402 2.34615 12.7727 2.53081 12.7727H3.21262C3.96547 12.7727 4.60822 12.5064 5.14089 11.9737C5.67356 11.4411 5.9399 10.7983 5.9399 10.0455V9.70455C5.9399 9.42046 5.84047 9.17898 5.6416 8.98011C5.44274 8.78125 5.20126 8.68182 4.91717 8.68182H2.53081C1.96262 8.68182 1.47967 8.48295 1.08194 8.08523C0.684215 7.6875 0.485352 7.20455 0.485352 6.63636V2.54545C0.485352 1.97727 0.684215 1.49432 1.08194 1.09659C1.47967 0.698864 1.96262 0.5 2.53081 0.5H6.62172C7.1899 0.5 7.67285 0.698864 8.07058 1.09659C8.46831 1.49432 8.66717 1.97727 8.66717 2.54545ZM18.2126 2.54545V10.0455C18.2126 10.7841 18.0688 11.489 17.7812 12.1602C17.4935 12.8313 17.1047 13.4119 16.6146 13.902C16.1246 14.392 15.5439 14.7809 14.8728 15.0685C14.2016 15.3562 13.4967 15.5 12.7581 15.5H12.0763C11.8916 15.5 11.7318 15.4325 11.5969 15.2976C11.4619 15.1626 11.3944 15.0028 11.3944 14.8182V13.4545C11.3944 13.2699 11.4619 13.1101 11.5969 12.9751C11.7318 12.8402 11.8916 12.7727 12.0763 12.7727H12.7581C13.5109 12.7727 14.1537 12.5064 14.6863 11.9737C15.219 11.4411 15.4854 10.7983 15.4854 10.0455V9.70455C15.4854 9.42046 15.3859 9.17898 15.1871 8.98011C14.9882 8.78125 14.7467 8.68182 14.4626 8.68182H12.0763C11.5081 8.68182 11.0251 8.48295 10.6274 8.08523C10.2297 7.6875 10.0308 7.20455 10.0308 6.63636V2.54545C10.0308 1.97727 10.2297 1.49432 10.6274 1.09659C11.0251 0.698864 11.5081 0.5 12.0763 0.5H16.1672C16.7354 0.5 17.2183 0.698864 17.616 1.09659C18.0138 1.49432 18.2126 1.97727 18.2126 2.54545Z" fill="#4F46E5" />
                      </svg>
                    </div>
                    <div className="hidden lg:block absolute left-12 top-1/2 transform -translate-y-1/2 w-96 h-px bg-gray-200" />
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">View your files</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat tempor con.</p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-indigo-600 w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={22} height={16} viewBox="0 0 22 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fillRule="evenodd" clipRule="evenodd" d="M20.5734 0.93934C21.1591 1.52513 21.1591 2.47487 20.5734 3.06066L8.57336 15.0607C7.98757 15.6464 7.03782 15.6464 6.45204 15.0607L0.452035 9.06066C-0.133751 8.47487 -0.133751 7.52513 0.452035 6.93934C1.03782 6.35355 1.98757 6.35355 2.57336 6.93934L7.5127 11.8787L18.452 0.93934C19.0378 0.353553 19.9876 0.353553 20.5734 0.93934Z" fill="white" />
                      </svg>
                    </div>
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">Get answers</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Lorem ipsum dolor sit amet consectetur adipiscing elit. Volutpat tempor con.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="py-28 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <h2 className="mb-20 text-6xl md:text-6xl xl:text-10xl text-center font-bold font-heading tracking-px-n leading-none">
              Our Team
            </h2>
            <div className="max-w-5xl mx-auto">
              <div className="flex flex-wrap -m-3">
                <div className="w-full md:w-1/3 p-3">
                  <div className="max-w-max mx-auto">
                    <div className="mb-6 max-w-max overflow-hidden rounded-3xl">
                      <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="https://media.licdn.com/dms/image/D4E03AQGwmmXiMjiTEw/profile-displayphoto-shrink_800_800/0/1674488452051?e=1681948800&v=beta&t=wFNqasbWhQ3q5Svk_3nN_JD4HVvCHfDKtaiQ5Anpqwo" alt="" />
                    </div>
                    <h3 className="mb-1 text-lg font-bold font-heading leading-snug">
                      Derek Armfield
                    </h3>
                    <p className="font-medium text-gray-600">Software Engineer</p>
                  </div>
                </div>
                <div className="w-full md:w-1/3 p-3">
                  <div className="max-w-max mx-auto">
                    <div className="mb-6 max-w-max overflow-hidden rounded-3xl">
                      <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="https://media.licdn.com/dms/image/D5603AQGSTpmMGJhOEQ/profile-displayphoto-shrink_400_400/0/1672102549279?e=1681948800&v=beta&t=-gpiO99ZPRHWVFSNeBErQD9TfNVnJuzCg_Du3l70S7w" alt="" />
                    </div>
                    <h3 className="mb-1 text-lg font-bold font-heading leading-snug">
                      Bek Omonkulov
                    </h3>
                    <p className="font-medium text-gray-600">Software Engineer</p>
                  </div>
                </div>
                <div className="w-full md:w-1/3 p-3">
                  <div className="max-w-max mx-auto">
                    <div className="mb-6 max-w-max overflow-hidden rounded-3xl">
                      <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="https://media.licdn.com/dms/image/C4D03AQHN-4lF5jF0cQ/profile-displayphoto-shrink_400_400/0/1516431402690?e=1681948800&v=beta&t=o9CcXgQBtJHL_hbOeLJaLXP2VjMzDA_VBkw4Q3VKM8E" alt="" />
                    </div>
                    <h3 className="mb-1 text-lg font-bold font-heading leading-snug">
                      Prahlad G Menon, PhD, PMP
                    </h3>
                    <p className="font-medium text-gray-600">AI Consultant, Innovator, Professor</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="pt-28 pb-32 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <p className="mb-5 text-sm text-indigo-600 font-semibold uppercase tracking-px">Frequently Asked questions</p>
            <h2 className="mb-16 text-6xl md:text-8xl xl:text-10xl font-bold font-heading tracking-px-n leading-none">Common Answers</h2>
            <div className="mb-8 md:max-w-5xl">
              <div className="flex flex-wrap -m-4">
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">1. How does Flaro help you in problems?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">2. What makes us look good?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">3. How to claim your 25% discount offer?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">4. How to get support for the product?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
              </div>
            </div>
            <a className="font-sans font-semibold text-indigo-600 hover:text-indigo-700 border-b border-indigo-600 hover:border-indigo-700" href="#">See all questions &amp; answers</a>
          </div>
        </section>

        <section className="py-32 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap -m-8">
              <div className="w-full md:w-5/12 p-8">
                <div className="flex flex-col justify-between h-full">
                  <div className="mb-8">
                    <h2 className="mb-5 text-6xl md:text-7xl font-bold font-heading tracking-px-n leading-tight">
                      Our Latest News and Articles
                    </h2>
                    <p className="text-gray-600 font-medium leading-relaxed">
                      Lorem ipsum dolor sit amet, consectetury adipiscing elit.
                      Volutpat, tempor to after condimentum commodo
                    </p>
                  </div>
                  <a className="inline-flex items-center text-indigo-600 hover:text-indigo-700 leading-normal" href="#">
                    <span className="mr-2 font-semibold">See all articles</span>
                    <svg width={18} height={18} viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M10.5 3.75L15.75 9M15.75 9L10.5 14.25M15.75 9L2.25 9" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </a>
                </div>
              </div>
              <div className="w-full md:flex-1 p-8">
                <div className="flex flex-wrap -m-3">
                  <div className="w-full md:w-1/2 p-3">
                    <div className="max-w-sm mx-auto">
                      <div className="mb-6 max-w-max overflow-hidden rounded-xl">
                        <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="flaro-assets/images/blog/blog-wide.png" alt="" />
                      </div>
                      <p className="mb-4 font-sans max-w-max px-3 py-1.5 text-sm text-indigo-600 font-semibold bg-indigo-50 uppercase rounded-md">
                        Business
                      </p>
                      <a className="mb-2 inline-block hover:text-gray-800 hover:underline" href="#">
                        <h3 className="text-xl font-bold font-heading leading-normal">
                          How to handle your good employee for the business.
                        </h3>
                      </a>
                      <p className="text-gray-600 font-medium leading-relaxed">
                        Lorem ipsum dolor sit amet, consectetury of a adipiscing elit.
                        Volutpat to a main.
                      </p>
                    </div>
                  </div>
                  <div className="w-full md:w-1/2 p-3">
                    <div className="max-w-sm mx-auto">
                      <div className="mb-6 max-w-max overflow-hidden rounded-xl">
                        <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="flaro-assets/images/blog/blog-wide2.png" alt="" />
                      </div>
                      <p className="mb-4 font-sans max-w-max px-3 py-1.5 text-sm text-indigo-600 font-semibold bg-indigo-50 uppercase rounded-md">
                        Productivity
                      </p>
                      <a className="mb-2 inline-block hover:text-gray-800 hover:underline" href="#">
                        <h3 className="text-xl font-bold font-heading leading-normal">
                          How startup company can help you to grow as a developer.
                        </h3>
                      </a>
                      <p className="text-gray-600 font-medium leading-relaxed">
                        Lorem ipsum dolor sit amet, consectetury of a adipiscing elit.
                        Volutpat to a main.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </div>





    </>
  )
}
