import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Disclosure, Transition } from "@headlessui/react";
import { Hero } from '@/components/hero';
import LogoCloud from '@/components/LogoCloud';
import Feature from '@/components/Feature';
import FeatureTwo from '@/components/FeatureTwo';
import Team from '@/components/Team';
import Faq from '@/components/Faq';
import Newsletter from '@/components/Newsletter';
import Footer from '@/components/Footer';
import Navbar from '@/components/Nav';
import Steps from '@/components/Steps';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const data = [
    {
      id: 1,
      question: "Is this component completely free to use?",
      answer: "No, it should be purchased first.",
    },
    {
      id: 2,
      question: "Can I use it in a commercial project?",
      answer: "Yes, once purchased, you can use it in any projects.",
    },
    {
      id: 3,
      question: "What is your refund policy?",
      answer:
        "If you are unhappy with your purchase for any reason, email us within 90 days and we wll refund you in full, no questions asked.",
    },
    {
      id: 4,
      question: "Do you offer technical support?",
      answer:
        "No, we don't offer technical support for components. Please purchase a support plan to get 6 months of support.",
    },
  ];


  return (
    <>
      <Head>
        <title>Viewer Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='max-w-screen-xl m-auto'>
        <Hero />
        <LogoCloud />
        <FeatureTwo />
        <Feature />
        <Steps />
        <Team />
        <Faq />
        
        {/* Removed newsletter for right now */}
        {/* <Newsletter /> */}
        {/* Removed newsletter for right now */}
      </div>
      <Footer />
    </>
  )
}
