import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Disclosure, Transition } from "@headlessui/react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const data = [
    {
      id: 1,
      question: "Is this component completely free to use?",
      answer: "No, it should be purchased first.",
    },
    {
      id: 2,
      question: "Can I use it in a commercial project?",
      answer: "Yes, once purchased, you can use it in any projects.",
    },
    {
      id: 3,
      question: "What is your refund policy?",
      answer:
        "If you are unhappy with your purchase for any reason, email us within 90 days and we wll refund you in full, no questions asked.",
    },
    {
      id: 4,
      question: "Do you offer technical support?",
      answer:
        "No, we don't offer technical support for components. Please purchase a support plan to get 6 months of support.",
    },
  ];


  return (
    <>
      <Head>
        <title>Viewer Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-screen-xl m-auto'>
        <section className="overflow-hidden">
          <div className="flex items-center justify-between px-7 xl:px-40 py-5 lg:py-7 bg-white">
            <div className="w-auto">
              <div className="flex flex-wrap items-center">
                <div className="w-auto mr-14">
                  <a href="#">
                    <img src="flaro-assets/logos/flaro-logo-black.svg" alt="" />
                  </a>
                </div>
              </div>
            </div>
            <div className="w-auto">
              <div className="flex flex-wrap items-center">
                <div className="w-auto hidden lg:block">
                  <ul className="flex items-center mr-16">
                    <li className="mr-9 font-medium hover:text-gray-700">
                      <a href="#">Features</a>
                    </li>
                    <li className="mr-9 font-medium hover:text-gray-700">
                      <a href="#">Solutions</a>
                    </li>
                    <li className="mr-9 font-medium hover:text-gray-700">
                      <a href="#">Resources</a>
                    </li>
                    <li className="font-medium hover:text-gray-700">
                      <a href="#">Pricing</a>
                    </li>
                  </ul>
                </div>
                <div className="w-auto lg:hidden">
                  <a href="#">
                    <svg className="navbar-burger text-indigo-600" width={51} height={51} viewBox="0 0 56 56" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <rect width={56} height={56} rx={28} fill="currentColor" />
                      <path d="M37 32H19M37 24H19" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div className="hidden navbar-menu fixed top-0 left-0 bottom-0 w-4/6 sm:max-w-xs z-50">
            <div className="navbar-backdrop fixed inset-0 bg-gray-800 opacity-80" />
            <nav className="relative z-10 px-9 pt-8 bg-white h-full overflow-y-auto">
              <div className="flex flex-wrap justify-between h-full">
                <div className="w-full">
                  <div className="flex items-center justify-between -m-2">
                    <div className="w-auto p-2">
                      <a className="inline-block" href="#">
                        <img src="flaro-assets/logos/flaro-logo-black.svg" alt="" />
                      </a>
                    </div>
                    <div className="w-auto p-2">
                      <a className="navbar-burger" href="#">
                        <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M6 18L18 6M6 6L18 18" stroke="#111827" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
                <div className="flex flex-col justify-center py-16 w-full">
                  <ul>
                    <li className="mb-12">
                      <a className="font-medium hover:text-gray-700" href="#">Features</a>
                    </li>
                    <li className="mb-12">
                      <a className="font-medium hover:text-gray-700" href="#">Solutions</a>
                    </li>
                    <li className="mb-12">
                      <a className="font-medium hover:text-gray-700" href="#">Resources</a>
                    </li>
                    <li>
                      <a className="font-medium hover:text-gray-700" href="#">Pricing</a>
                    </li>
                  </ul>
                </div>
                <div className="flex flex-col justify-end w-full pb-8">
                  <div className="flex flex-wrap">
                    <div className="w-full">
                      <div className="block">
                        <button className="py-3 px-5 w-full text-white font-semibold rounded-xl focus:ring focus:ring-indigo-300 bg-indigo-600 hover:bg-indigo-700 transition ease-in-out duration-200" type="button">
                          Try 14 Days Free Trial
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </section>
        <section className="pt-24 pb-28 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <h2 className="mb-7 text-6xl md:text-8xl xl:text-10xl font-bold font-heading text-center tracking-px-n leading-none">
              Inference analysis made easy
            </h2>
            <p className="mb-14 text-lg text-gray-600 font-medium text-center mx-auto md:max-w-2xl">
              Looking to better analyze medical volumes or understand your AI model's inference? Our private, 
              zero-footprint, web based renderer can help. 
            </p>
            <div className="flex justify-center">
              <div className="inline-block">
                <img className="mb-11 mx-auto max-h-96 transform hover:translate-y-3 transition ease-in-out duration-1000" src="viewer_example.png" alt="" />
                <ul className="flex flex-wrap justify-center -m-8">
                  <li className="w-auto p-8">
                    <a className="text-sm text-indigo-600 hover:text-indigo-700 font-semibold uppercase tracking-px" href="#">Real-time Analytics</a>
                  </li>
                  <li className="w-auto p-8">
                    <a className="text-sm text-gray-400 hover:text-gray-500 font-semibold uppercase tracking-px" href="#">Easy Projects</a>
                  </li>
                  <li className="w-auto p-8">
                    <a className="text-sm text-gray-400 hover:text-gray-500 font-semibold uppercase tracking-px" href="#">Email Notification</a>
                  </li>
                  <li className="w-auto p-8">
                    <a className="text-sm text-gray-400 hover:text-gray-500 font-semibold uppercase tracking-px" href="#">Cloud Servers</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="relative pt-28 pb-36 bg-blueGray-100 overflow-hidden">
          <img className="absolute top-0 left-0" src="flaro-assets/images/logos/gradient3.svg" alt="" />
          <div className="relative z-10 container px-4 mx-auto">
            <p className="mb-14 text-sm text-gray-600 text-center font-semibold uppercase tracking-px">
              Powering next-gen companies
            </p>
            <div className="flex flex-wrap max-w-5xl mx-auto -m-3">
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl2.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl3.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl4.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl5.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl6.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl7.png" alt="" />
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-3">
                <div className="flex items-center justify-center py-8 px-9 h-full bg-white rounded-3xl">
                  <img src="flaro-assets/logos/brands/logo-xxl8.png" alt="" />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-36 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap xl:items-center -m-8">
              <div className="w-full md:w-1/2 p-8">
                <img className="mx-auto transform hover:translate-y-3 transition ease-in-out duration-1000" src="flaro-assets/images/features/upgrade.png" alt="" />
              </div>
              <div className="w-full md:w-1/2 p-8">
                <div className="md:max-w-xl">
                  <p className="mb-7 text-sm text-gray-600 font-semibold uppercase tracking-px">
                    👋 Meet new Flaro
                  </p>
                  <h2 className="mb-32 text-6xl md:text-7xl font-bold font-heading tracking-px-n leading-tight">
                    Upgrade to pro to unlock all features.
                  </h2>
                  <div className="flex flex-wrap mb-5 -m-8">
                    <div className="w-full md:w-1/2 p-8">
                      <div className="md:max-w-xs">
                        <div className="flex flex-wrap -m-2">
                          <div className="w-auto p-2">
                            <svg className="mt-1" width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M9 3V5M15 3V5M9 19V21M15 19V21M5 9H3M5 15H3M21 9H19M21 15H19M7 19H17C18.1046 19 19 18.1046 19 17V7C19 5.89543 18.1046 5 17 5H7C5.89543 5 5 5.89543 5 7V17C5 18.1046 5.89543 19 7 19ZM9 9H15V15H9V9Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          </div>
                          <div className="flex-1 p-2">
                            <h3 className="mb-2 text-xl font-semibold leading-normal">
                              Analytical
                            </h3>
                            <p className="text-gray-600 font-medium leading-relaxed">
                              Lorem ipsum dolor sit amet, to the consectr adipis.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="w-full md:w-1/2 p-8">
                      <div className="md:max-w-xs">
                        <div className="flex flex-wrap -m-2">
                          <div className="w-auto p-2">
                            <svg className="mt-1" width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path d="M16 8V16M12 11V16M8 14V16M6 20H18C19.1046 20 20 19.1046 20 18V6C20 4.89543 19.1046 4 18 4H6C4.89543 4 4 4.89543 4 6V18C4 19.1046 4.89543 20 6 20Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                          </div>
                          <div className="flex-1 p-2">
                            <h3 className="mb-2 text-xl font-semibold leading-normal">
                              Dashboards
                            </h3>
                            <p className="text-gray-600 font-medium leading-relaxed">
                              Lorem ipsum dolor sit amet, to the consectr adipis.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="md:inline-block">
                    <button className="py-4 px-6 w-full text-white font-semibold border border-indigo-700 rounded-xl shadow-4xl focus:ring focus:ring-indigo-300 bg-indigo-600 hover:bg-indigo-700 transition ease-in-out duration-200" type="button">
                      Get Started Now
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-32 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap items-center -m-8">
              <div className="w-full md:w-1/2 p-8">
                <h2 className="mb-9 text-6xl md:text-8xl xl:text-10xl font-bold font-heading tracking-px-n leading-none">
                  Get down to your business
                </h2>
                <p className="mb-10 text-lg text-gray-900 font-medium leading-relaxed md:max-w-md">
                  Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet
                  sint. Velit officia consequat duis enim velit mollit. Exercitation
                  veniam consequat.
                </p>
                <div className="mb-11 md:inline-block rounded-xl shadow-4xl">
                  <button className="py-4 px-6 w-full text-white font-semibold border border-indigo-700 rounded-xl focus:ring focus:ring-indigo-300 bg-indigo-600 hover:bg-indigo-700 transition ease-in-out duration-200" type="button">
                    Learn How to Save More
                  </button>
                </div>
                <div className="flex flex-wrap -m-2">
                  <div className="w-auto p-2">
                    <img src="flaro-assets/images/features/money-coins.png" alt="" />
                  </div>
                  <div className="flex-1 p-2">
                    <p className="text-gray-600 font-medium md:max-w-sm">
                      Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                      amet sint. Velit officia consequat duis enim velit mollit.
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 p-8">
                <img className="transform hover:-translate-x-16 transition ease-in-out duration-1000" src="flaro-assets/images/features/feature2.png" alt="" />
              </div>
            </div>
          </div>
        </section>
        <section className="relative pt-28 pb-24 bg-white overflow-hidden">
          <img className="absolute left-1/2 top-0 transform -translate-x-1/2" src="flaro-assets/images/how-it-works/gradient2.svg" alt="" />
          <div className="relative z-10 container px-4 mx-auto">
            <p className="mb-6 text-sm text-indigo-600 text-center font-semibold uppercase tracking-px">How this works</p>
            <h2 className="mb-20 text-3xl md:text-5xl text-center font-bold font-heading tracking-px-n leading-tight">We make things easy for you</h2>
            <div className="flex flex-wrap -m-8">
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-white w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={22} height={22} viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M2.75 9.16658H19.25M6.41667 13.7499H7.33333M11 13.7499H11.9167M5.5 17.4166H16.5C18.0188 17.4166 19.25 16.1854 19.25 14.6666V7.33325C19.25 5.81447 18.0188 4.58325 16.5 4.58325H5.5C3.98122 4.58325 2.75 5.81447 2.75 7.33325V14.6666C2.75 16.1854 3.98122 17.4166 5.5 17.4166Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                    <div className="hidden lg:block absolute left-12 top-1/2 transform -translate-y-1/2 w-96 h-px bg-gray-200" />
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">Generate Model Inference</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Generate an inference from your volume and extract a heatmap</p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-white w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={24} height={24} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M16 8V16M12 11V16M8 14V16M6 20H18C19.1046 20 20 19.1046 20 18V6C20 4.89543 19.1046 4 18 4H6C4.89543 4 4 4.89543 4 6V18C4 19.1046 4.89543 20 6 20Z" stroke="#4F46E5" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                    <div className="hidden lg:block absolute left-12 top-1/2 transform -translate-y-1/2 w-96 h-px bg-gray-200" />
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">Upload volume</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Upload your medical volume to the viewer for rendering</p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-white w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={19} height={16} viewBox="0 0 19 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8.66717 2.54545V10.0455C8.66717 10.7841 8.52335 11.489 8.23571 12.1602C7.94807 12.8313 7.55922 13.4119 7.06916 13.902C6.5791 14.392 5.99849 14.7809 5.32733 15.0685C4.65616 15.3562 3.95126 15.5 3.21262 15.5H2.53081C2.34615 15.5 2.18635 15.4325 2.0514 15.2976C1.91646 15.1626 1.84899 15.0028 1.84899 14.8182V13.4545C1.84899 13.2699 1.91646 13.1101 2.0514 12.9751C2.18635 12.8402 2.34615 12.7727 2.53081 12.7727H3.21262C3.96547 12.7727 4.60822 12.5064 5.14089 11.9737C5.67356 11.4411 5.9399 10.7983 5.9399 10.0455V9.70455C5.9399 9.42046 5.84047 9.17898 5.6416 8.98011C5.44274 8.78125 5.20126 8.68182 4.91717 8.68182H2.53081C1.96262 8.68182 1.47967 8.48295 1.08194 8.08523C0.684215 7.6875 0.485352 7.20455 0.485352 6.63636V2.54545C0.485352 1.97727 0.684215 1.49432 1.08194 1.09659C1.47967 0.698864 1.96262 0.5 2.53081 0.5H6.62172C7.1899 0.5 7.67285 0.698864 8.07058 1.09659C8.46831 1.49432 8.66717 1.97727 8.66717 2.54545ZM18.2126 2.54545V10.0455C18.2126 10.7841 18.0688 11.489 17.7812 12.1602C17.4935 12.8313 17.1047 13.4119 16.6146 13.902C16.1246 14.392 15.5439 14.7809 14.8728 15.0685C14.2016 15.3562 13.4967 15.5 12.7581 15.5H12.0763C11.8916 15.5 11.7318 15.4325 11.5969 15.2976C11.4619 15.1626 11.3944 15.0028 11.3944 14.8182V13.4545C11.3944 13.2699 11.4619 13.1101 11.5969 12.9751C11.7318 12.8402 11.8916 12.7727 12.0763 12.7727H12.7581C13.5109 12.7727 14.1537 12.5064 14.6863 11.9737C15.219 11.4411 15.4854 10.7983 15.4854 10.0455V9.70455C15.4854 9.42046 15.3859 9.17898 15.1871 8.98011C14.9882 8.78125 14.7467 8.68182 14.4626 8.68182H12.0763C11.5081 8.68182 11.0251 8.48295 10.6274 8.08523C10.2297 7.6875 10.0308 7.20455 10.0308 6.63636V2.54545C10.0308 1.97727 10.2297 1.49432 10.6274 1.09659C11.0251 0.698864 11.5081 0.5 12.0763 0.5H16.1672C16.7354 0.5 17.2183 0.698864 17.616 1.09659C18.0138 1.49432 18.2126 1.97727 18.2126 2.54545Z" fill="#4F46E5" />
                      </svg>
                    </div>
                    <div className="hidden lg:block absolute left-12 top-1/2 transform -translate-y-1/2 w-96 h-px bg-gray-200" />
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">Overlay Heatmap</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">From your model&apos;s inference, overlay your heatmap</p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-1/2 lg:w-1/4 p-8">
                <div className="text-center">
                  <div className="relative z-10 bg-indigo-600 w-12 h-12 mb-8 mx-auto border border-blueGray-200 rounded-full">
                    <div className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2">
                      <svg width={22} height={16} viewBox="0 0 22 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fillRule="evenodd" clipRule="evenodd" d="M20.5734 0.93934C21.1591 1.52513 21.1591 2.47487 20.5734 3.06066L8.57336 15.0607C7.98757 15.6464 7.03782 15.6464 6.45204 15.0607L0.452035 9.06066C-0.133751 8.47487 -0.133751 7.52513 0.452035 6.93934C1.03782 6.35355 1.98757 6.35355 2.57336 6.93934L7.5127 11.8787L18.452 0.93934C19.0378 0.353553 19.9876 0.353553 20.5734 0.93934Z" fill="white" />
                      </svg>
                    </div>
                  </div>
                  <div className="md:max-w-xs mx-auto">
                    <h3 className="mb-4 font-heading text-xl font-bold font-heading leading-normal">View your files</h3>
                    <p className="text-gray-600 font-medium leading-relaxed">Use our built in slice, window, and levels to inspect your data</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="py-28 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <h2 className="mb-20 text-6xl md:text-6xl xl:text-10xl text-center font-bold font-heading tracking-px-n leading-none">
              Our Team
            </h2>
            <div className="max-w-5xl mx-auto">
              <div className="flex flex-wrap -m-3">
                <div className="w-full md:w-1/3 p-3">
                  <div className="max-w-max mx-auto">
                    <div className="mb-6 max-w-max overflow-hidden rounded-3xl">
                      <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="https://media.licdn.com/dms/image/D4E03AQGwmmXiMjiTEw/profile-displayphoto-shrink_800_800/0/1674488452051?e=1681948800&v=beta&t=wFNqasbWhQ3q5Svk_3nN_JD4HVvCHfDKtaiQ5Anpqwo" alt="" />
                    </div>
                    <h3 className="mb-1 text-lg font-bold font-heading leading-snug">
                      Derek Armfield
                    </h3>
                    <p className="font-medium text-gray-600">Software Engineer</p>
                  </div>
                </div>
                <div className="w-full md:w-1/3 p-3">
                  <div className="max-w-max mx-auto">
                    <div className="mb-6 max-w-max overflow-hidden rounded-3xl">
                      <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="https://media.licdn.com/dms/image/D5603AQGSTpmMGJhOEQ/profile-displayphoto-shrink_400_400/0/1672102549279?e=1681948800&v=beta&t=-gpiO99ZPRHWVFSNeBErQD9TfNVnJuzCg_Du3l70S7w" alt="" />
                    </div>
                    <h3 className="mb-1 text-lg font-bold font-heading leading-snug">
                      Bek Omonkulov
                    </h3>
                    <p className="font-medium text-gray-600">Software Engineer</p>
                  </div>
                </div>
                <div className="w-full md:w-1/3 p-3">
                  <div className="max-w-max mx-auto">
                    <div className="mb-6 max-w-max overflow-hidden rounded-3xl">
                      <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="https://media.licdn.com/dms/image/C4D03AQHN-4lF5jF0cQ/profile-displayphoto-shrink_400_400/0/1516431402690?e=1681948800&v=beta&t=o9CcXgQBtJHL_hbOeLJaLXP2VjMzDA_VBkw4Q3VKM8E" alt="" />
                    </div>
                    <h3 className="mb-1 text-lg font-bold font-heading leading-snug">
                      Prahlad G Menon, PhD, PMP
                    </h3>
                    <p className="font-medium text-gray-600">AI Consultant, Innovator, Professor</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="pt-28 pb-32 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <p className="mb-5 text-sm text-indigo-600 font-semibold uppercase tracking-px">Frequently Asked questions</p>
            <h2 className="mb-16 text-6xl md:text-8xl xl:text-10xl font-bold font-heading tracking-px-n leading-none">Common Answers</h2>
            <div className="mb-8 md:max-w-5xl">
              <div className="flex flex-wrap -m-4">
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">1. How does Flaro help you in problems?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">2. What makes us look good?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">3. How to claim your 25% discount offer?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
                <div className="w-full md:w-1/2 p-4">
                  <div className="p-6 border border-gray-200 rounded-2xl shadow-10xl">
                    <h3 className="mb-4 text-lg font-semibold leading-normal">4. How to get support for the product?</h3>
                    <p className="font-sans text-gray-600 leading-relaxed">Lorem ipsum dolor sit amet, to the consectr adipiscing elit. Volutpat tempor condimentum vitae vel purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
              </div>
            </div>
            <a className="font-sans font-semibold text-indigo-600 hover:text-indigo-700 border-b border-indigo-600 hover:border-indigo-700" href="#">See all questions &amp; answers</a>
          </div>
        </section>

        <section className="py-32 bg-white overflow-hidden">
          <div className="container px-4 mx-auto">
            <div className="flex flex-wrap -m-8">
              <div className="w-full md:w-5/12 p-8">
                <div className="flex flex-col justify-between h-full">
                  <div className="mb-8">
                    <h2 className="mb-5 text-6xl md:text-7xl font-bold font-heading tracking-px-n leading-tight">
                      Our Latest News and Articles
                    </h2>
                    <p className="text-gray-600 font-medium leading-relaxed">
                      Lorem ipsum dolor sit amet, consectetury adipiscing elit.
                      Volutpat, tempor to after condimentum commodo
                    </p>
                  </div>
                  <a className="inline-flex items-center text-indigo-600 hover:text-indigo-700 leading-normal" href="#">
                    <span className="mr-2 font-semibold">See all articles</span>
                    <svg width={18} height={18} viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M10.5 3.75L15.75 9M15.75 9L10.5 14.25M15.75 9L2.25 9" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                  </a>
                </div>
              </div>
              <div className="w-full md:flex-1 p-8">
                <div className="flex flex-wrap -m-3">
                  <div className="w-full md:w-1/2 p-3">
                    <div className="max-w-sm mx-auto">
                      <div className="mb-6 max-w-max overflow-hidden rounded-xl">
                        <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="flaro-assets/images/blog/blog-wide.png" alt="" />
                      </div>
                      <p className="mb-4 font-sans max-w-max px-3 py-1.5 text-sm text-indigo-600 font-semibold bg-indigo-50 uppercase rounded-md">
                        Business
                      </p>
                      <a className="mb-2 inline-block hover:text-gray-800 hover:underline" href="#">
                        <h3 className="text-xl font-bold font-heading leading-normal">
                          How to handle your good employee for the business.
                        </h3>
                      </a>
                      <p className="text-gray-600 font-medium leading-relaxed">
                        Lorem ipsum dolor sit amet, consectetury of a adipiscing elit.
                        Volutpat to a main.
                      </p>
                    </div>
                  </div>
                  <div className="w-full md:w-1/2 p-3">
                    <div className="max-w-sm mx-auto">
                      <div className="mb-6 max-w-max overflow-hidden rounded-xl">
                        <img className="transform hover:scale-105 transition ease-in-out duration-1000" src="flaro-assets/images/blog/blog-wide2.png" alt="" />
                      </div>
                      <p className="mb-4 font-sans max-w-max px-3 py-1.5 text-sm text-indigo-600 font-semibold bg-indigo-50 uppercase rounded-md">
                        Productivity
                      </p>
                      <a className="mb-2 inline-block hover:text-gray-800 hover:underline" href="#">
                        <h3 className="text-xl font-bold font-heading leading-normal">
                          How startup company can help you to grow as a developer.
                        </h3>
                      </a>
                      <p className="text-gray-600 font-medium leading-relaxed">
                        Lorem ipsum dolor sit amet, consectetury of a adipiscing elit.
                        Volutpat to a main.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </div>
      <section className="relative pt-24 bg-black overflow-hidden">
        <img className="absolute left-1/2 bottom-0 h-full transform -translate-x-1/2" src="flaro-assets/images/footers/gradient.svg" alt="" />
        <div className="relative z-10 container px-4 mx-auto">
          <div className="pb-24 border-b border-gray-900 ">
            <div className="flex flex-wrap -m-8   max-w-screen-xl m-auto">
              <div className="w-full sm:w-1/2 lg:w-6/12 p-8">
                <div className="lg:max-w-sm">
                  <a className="mb-8 inline-block" href="#">
                    <img src="flaro-assets/logos/flaro-logo-light.svg" alt="" />
                  </a>
                  <p className="mb-20 text-gray-400 font-medium leading-relaxed md:max-w-xs">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lectus
                    interdum facilisis odio scelerisque vel neque.
                  </p>
                  <div className="flex flex-wrap -m-1.5">
                    <div className="w-auto p-1.5">
                      <a href="#">
                        <div className="flex items-center justify-center w-9 h-9 border border-gray-800 hover:border-gray-900 rounded-full">
                          <svg width={9} height={16} viewBox="0 0 9 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.81589 5.30371L5.81589 3.80371C5.81589 3.15371 5.97379 2.80371 7.07905 2.80371H8.44747V0.303711L6.34221 0.303711C3.71063 0.303711 2.658 1.95371 2.658 3.80371V5.30371H0.552734L0.552734 7.80371H2.658L2.658 15.3037H5.81589L5.81589 7.80371H8.13168L8.44747 5.30371H5.81589Z" fill="#D4D4D8" />
                          </svg>
                        </div>
                      </a>
                    </div>
                    <div className="w-auto p-1.5">
                      <a href="#">
                        <div className="flex items-center justify-center w-9 h-9 border border-gray-800 hover:border-gray-900 rounded-full">
                          <svg width={15} height={13} viewBox="0 0 15 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M14.8462 2.25418C14.306 2.48722 13.7182 2.65493 13.1126 2.72025C13.7413 2.34675 14.2121 1.75669 14.4367 1.06076C13.8467 1.41171 13.2004 1.6578 12.5265 1.78811C12.2448 1.48698 11.9041 1.24708 11.5257 1.08337C11.1472 0.919662 10.7391 0.835644 10.3268 0.836555C8.65848 0.836555 7.31676 2.18886 7.31676 3.84835C7.31676 4.08139 7.34501 4.31442 7.39091 4.53863C4.89285 4.40799 2.6649 3.21457 1.18372 1.38736C0.913833 1.84834 0.772403 2.37322 0.774144 2.90739C0.774144 3.95251 1.30553 4.87406 2.11586 5.41604C1.63832 5.39724 1.17197 5.26598 0.754725 5.03295V5.07002C0.754725 6.53355 1.78926 7.74639 3.16804 8.02533C2.90916 8.09257 2.64285 8.12697 2.37537 8.12772C2.17941 8.12772 1.99404 8.1083 1.80691 8.08182C2.18824 9.27524 3.29868 10.1421 4.62098 10.1703C3.58645 10.9806 2.29063 11.4573 0.8836 11.4573C0.631146 11.4573 0.398112 11.4485 0.15625 11.4202C1.4909 12.2764 3.07448 12.7708 4.77987 12.7708C10.3162 12.7708 13.3456 8.18421 13.3456 4.2032C13.3456 4.07256 13.3456 3.94192 13.3368 3.81128C13.9229 3.38228 14.4367 2.85089 14.8462 2.25418Z" fill="#D4D4D8" />
                          </svg>
                        </div>
                      </a>
                    </div>
                    <div className="w-auto p-1.5">
                      <a href="#">
                        <div className="flex items-center justify-center w-9 h-9 border border-gray-800 hover:border-gray-900 rounded-full">
                          <svg width={17} height={17} viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8.5 0.803711C6.329 0.803711 6.056 0.813711 5.203 0.851711C4.35 0.891711 3.769 1.02571 3.26 1.22371C2.72609 1.42453 2.24249 1.73954 1.843 2.14671C1.43608 2.54641 1.12111 3.02995 0.92 3.56371C0.722 4.07171 0.587 4.65371 0.548 5.50371C0.51 6.35871 0.5 6.63071 0.5 8.80471C0.5 10.9767 0.51 11.2487 0.548 12.1017C0.588 12.9537 0.722 13.5347 0.92 14.0437C1.125 14.5697 1.398 15.0157 1.843 15.4607C2.287 15.9057 2.733 16.1797 3.259 16.3837C3.769 16.5817 4.349 16.7167 5.201 16.7557C6.055 16.7937 6.327 16.8037 8.5 16.8037C10.673 16.8037 10.944 16.7937 11.798 16.7557C12.649 16.7157 13.232 16.5817 13.741 16.3837C14.2746 16.1828 14.7578 15.8678 15.157 15.4607C15.602 15.0157 15.875 14.5697 16.08 14.0437C16.277 13.5347 16.412 12.9537 16.452 12.1017C16.49 11.2487 16.5 10.9767 16.5 8.80371C16.5 6.63071 16.49 6.35871 16.452 5.50471C16.412 4.65371 16.277 4.07171 16.08 3.56371C15.8789 3.02994 15.5639 2.54639 15.157 2.14671C14.7576 1.73939 14.274 1.42436 13.74 1.22371C13.23 1.02571 12.648 0.890711 11.797 0.851711C10.943 0.813711 10.672 0.803711 8.498 0.803711H8.501H8.5ZM7.783 2.24571H8.501C10.637 2.24571 10.89 2.25271 11.733 2.29171C12.513 2.32671 12.937 2.45771 13.219 2.56671C13.592 2.71171 13.859 2.88571 14.139 3.16571C14.419 3.44571 14.592 3.71171 14.737 4.08571C14.847 4.36671 14.977 4.79071 15.012 5.57071C15.051 6.41371 15.059 6.66671 15.059 8.80171C15.059 10.9367 15.051 11.1907 15.012 12.0337C14.977 12.8137 14.846 13.2367 14.737 13.5187C14.6087 13.8661 14.404 14.1801 14.138 14.4377C13.858 14.7177 13.592 14.8907 13.218 15.0357C12.938 15.1457 12.514 15.2757 11.733 15.3117C10.89 15.3497 10.637 15.3587 8.501 15.3587C6.365 15.3587 6.111 15.3497 5.268 15.3117C4.488 15.2757 4.065 15.1457 3.783 15.0357C3.4355 14.9076 3.12113 14.7033 2.863 14.4377C2.59675 14.1797 2.39172 13.8654 2.263 13.5177C2.154 13.2367 2.023 12.8127 1.988 12.0327C1.95 11.1897 1.942 10.9367 1.942 8.79971C1.942 6.66371 1.95 6.41171 1.988 5.56871C2.024 4.78871 2.154 4.36471 2.264 4.08271C2.409 3.70971 2.583 3.44271 2.863 3.16271C3.143 2.88271 3.409 2.70971 3.783 2.56471C4.065 2.45471 4.488 2.32471 5.268 2.28871C6.006 2.25471 6.292 2.24471 7.783 2.24371V2.24571ZM12.771 3.57371C12.6449 3.57371 12.5201 3.59854 12.4036 3.64679C12.2872 3.69503 12.1813 3.76574 12.0922 3.85489C12.003 3.94403 11.9323 4.04986 11.8841 4.16633C11.8358 4.28281 11.811 4.40764 11.811 4.53371C11.811 4.65978 11.8358 4.78461 11.8841 4.90109C11.9323 5.01756 12.003 5.12339 12.0922 5.21253C12.1813 5.30168 12.2872 5.37239 12.4036 5.42064C12.5201 5.46888 12.6449 5.49371 12.771 5.49371C13.0256 5.49371 13.2698 5.39257 13.4498 5.21253C13.6299 5.0325 13.731 4.78832 13.731 4.53371C13.731 4.2791 13.6299 4.03492 13.4498 3.85489C13.2698 3.67485 13.0256 3.57371 12.771 3.57371ZM8.501 4.69571C7.95607 4.68721 7.41489 4.7872 6.90898 4.98985C6.40306 5.19251 5.94251 5.49378 5.55415 5.87613C5.16579 6.25849 4.85736 6.71428 4.64684 7.21697C4.43632 7.71966 4.3279 8.25921 4.3279 8.80421C4.3279 9.34921 4.43632 9.88876 4.64684 10.3915C4.85736 10.8941 5.16579 11.3499 5.55415 11.7323C5.94251 12.1146 6.40306 12.4159 6.90898 12.6186C7.41489 12.8212 7.95607 12.9212 8.501 12.9127C9.57954 12.8959 10.6082 12.4556 11.365 11.687C12.1217 10.9183 12.5459 9.88288 12.5459 8.80421C12.5459 7.72554 12.1217 6.69012 11.365 5.92146C10.6082 5.1528 9.57954 4.71254 8.501 4.69571ZM8.501 6.13671C9.20833 6.13671 9.88669 6.4177 10.3869 6.91786C10.887 7.41802 11.168 8.09638 11.168 8.80371C11.168 9.51104 10.887 10.1894 10.3869 10.6896C9.88669 11.1897 9.20833 11.4707 8.501 11.4707C7.79367 11.4707 7.11531 11.1897 6.61515 10.6896C6.11499 10.1894 5.834 9.51104 5.834 8.80371C5.834 8.09638 6.11499 7.41802 6.61515 6.91786C7.11531 6.4177 7.79367 6.13671 8.501 6.13671Z" fill="#D4D4D8" />
                          </svg>
                        </div>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="w-full sm:w-1/2 lg:w-2/12 p-8">
                <h3 className="mb-8 text-sm text-gray-600 uppercase font-semibold leading-normal tracking-px">
                  Products
                </h3>
                <ul>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Services</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">About Us</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">News &amp; Stories</a>
                  </li>
                  <li>
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Roadmap</a>
                  </li>
                </ul>
              </div>
              <div className="w-full sm:w-1/2 lg:w-2/12 p-8">
                <h3 className="mb-8 text-sm text-gray-600 uppercase font-semibold leading-normal tracking-px">
                  Important links
                </h3>
                <ul>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Our Journeys</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Pricing Plans</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Roadmap</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Terms &amp; Conditions</a>
                  </li>
                  <li>
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Privacy Policy</a>
                  </li>
                </ul>
              </div>
              <div className="w-full sm:w-1/2 lg:w-2/12 p-8">
                <h3 className="mb-8 text-sm text-gray-600 uppercase font-semibold leading-normal tracking-px">
                  Company
                </h3>
                <ul>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">About Us</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Jobs</a>
                  </li>
                  <li className="mb-5">
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Press</a>
                  </li>
                  <li>
                    <a className="text-white hover:text-gray-200 font-medium leading-relaxed" href="#">Contact Us</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <p className="py-5 text-sm text-gray-300 font-medium text-center leading-normal">
            Copyright © 2022 Flaro. All Rights Reserved
          </p>
        </div>
      </section>

    </>
  )
}
